### ISSUE TITLE
Installation fails on a machine with less memory

### ISSUE THREAD

**Issue by BLACKFLAGX** [txthinking/nami#10]
`Downloading 100.00%                                                    2.2s 152903680/152903680
error: Uncaught (in promise) RangeError: Array buffer allocation failed
    var b = new Uint8Array(l);
            ^
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at download (https://raw.githubusercontent.com/txthinking/nami/master/nami.js:20:13)
    at async Object.download_command_from_url (https://raw.githubusercontent.com/txthinking/nami/master/nami.js:42:13)
    at async https://raw.githubusercontent.com/txthinking/nami/master/package/nami.js:19:5
exit status 1`

Can you optimize it, or told me how much memory is more suitable for a machine

**Comment by txthinking** [comment]
Looks like I should use zero copy to reduce memory

**Comment by txthinking** [comment]
please try again

**Comment by BLACKFLAGX** [comment]
yes, i have released memory and the installation was finished successfully.
