### ISSUE TITLE
`nami install nami` fails of MinGW-w64

### ISSUE THREAD

**Issue by sskras** [txthinking/nami#13]
I just installed it and run following:
```
saukrs@DESKTOP-O7JE7JE MINGW64 ~
$ nami install nami
Download https://raw.githubusercontent.com/txthinking/nami/master/package/nami.js
Download https://raw.githubusercontent.com/txthinking/nami/master/nami.js
Download https://raw.githubusercontent.com/denoland/deno_std/0.118.0/fmt/colors.ts
Download https://raw.githubusercontent.com/txthinking/progress/nami1.2.3/mod.ts
Download https://raw.githubusercontent.com/txthinking/progress/nami1.2.3/multi.ts
Download https://raw.githubusercontent.com/denoland/deno_std/0.79.0/fmt/colors.ts
Check https://raw.githubusercontent.com/txthinking/nami/master/package/nami.js
nami has been open sourced on https://github.com/txthinking/nami
Fetching https://api.github.com/repos/txthinking/nami/releases/latest
error: Uncaught (in promise) NotFound: The system cannot find the path specified. (os error 3), open 'C:\msys64\home\saukrs/.nami/cache/version'
            await Deno.writeFile(`${Deno.env.get("HOME")}/.nami/cache/version`, new TextEncoder().encode(version));
            ^
    at async open (deno:runtime/js/40_files.js:51:17)
    at async Object.writeFile (deno:runtime/js/40_write_file.js:62:18)
    at async Object.version (https://raw.githubusercontent.com/txthinking/nami/master/nami.js:29:13)
    at async https://raw.githubusercontent.com/txthinking/nami/master/package/nami.js:8:1
exit status 1
```

This is my system:
```
saukrs@DESKTOP-O7JE7JE MINGW64 ~
$ uname -a
MINGW64_NT-10.0-19042 DESKTOP-O7JE7JE 3.3.3-341.x86_64 2022-01-18 13:00 UTC x86_64 Msys
```

**Comment by sskras** [comment]
And this is the installation log:
```
saukrs@DESKTOP-O7JE7JE MINGW64 ~
$ bash -x <(curl https://bash.ooo/nami.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   982  100   982    0     0   6233      0 --:--:-- --:--:-- --:--:--  6294+ os=
+ arch=

++ uname -s
+ '[' MINGW64_NT-10.0-19042 = Darwin ']'
++ uname -s
+ '[' MINGW64_NT-10.0-19042 = Linux ']'
++ uname -s
++ grep MINGW
++ wc -l
+ '[' 1 -eq 1 ']'
+ os=windows
++ uname -m
+ '[' x86_64 = x86_64 ']'
+ arch=amd64
++ uname -m
+ '[' x86_64 = arm64 ']'
++ uname -m
+ '[' x86_64 = aarch64 ']'
+ '[' windows = '' -o amd64 = '' ']'
+ sfx=
+ '[' windows = windows ']'
+ sfx=.exe
+ mkdir -p /home/saukrs/.nami/bin
+ curl -L -o /home/saukrs/.nami/bin/nami.exe https://github.com/txthinking/nami/releases/latest/download/nami_windows_amd64.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151  100   151    0     0    682      0 --:--:-- --:--:-- --:--:--   686
100   661  100   661    0     0   2311      0 --:--:-- --:--:-- --:--:--  2311
100  145M  100  145M    0     0   727k      0  0:03:25  0:03:25 --:--:--  707k
+ chmod +x /home/saukrs/.nami/bin/nami
+ echo 'export PATH=$HOME/.nami/bin:$PATH'
+ echo 'export PATH=$HOME/.nami/bin:$PATH'
+ echo 'export PATH=$HOME/.nami/bin:$PATH'
+ exec -l /usr/bin/bash
```

**Comment by txthinking** [comment]
```
$ echo $HOME
/c/Users/myname

$ ls $HOME/.nami
bin/  cache/  db
```

It looks like your $HOME is `/c/msys64/home/saukrs`, did you change something?

**Comment by txthinking** [comment]
Can you try this two commands and send the result to here:
```
echo $HOME
deno eval 'console.log(Deno.env.get("HOME"))'
```

**Comment by txthinking** [comment]
try v20220601
